In [1]:
import sys
sys.path.append('..')
import torch
from models.fc_model import FC_regressor, FC_model

In [2]:
model = FC_model(4096, 5, sizes=[1000,100,100,1000,4096], bias = False, use_batchnorm= True, dropout= 0.1 )

In [3]:
print(model)

FC_model(
  (layers_real): ModuleList(
    (0): Linear(in_features=4096, out_features=1000, bias=False)
    (1): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=1000, out_features=100, bias=False)
    (5): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.1, inplace=False)
    (8): Linear(in_features=100, out_features=100, bias=False)
    (9): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Dropout(p=0.1, inplace=False)
    (12): Linear(in_features=100, out_features=1000, bias=False)
    (13): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (14): ReLU()
    (15): Dropout(p=0.1, inplace=False)
    (16): Linear(in_features=1000, out_features=4096, bias=False)
  )
  (layers_imag): ModuleList(
    (0): Linear(in_features=

In [4]:
x = torch.rand((32,1,4096)) + 1j*torch.rand((32,1,4096))

In [5]:
model(x.real, x.imag)

(tensor([[[-0.0628, -0.5085,  0.2706,  ...,  0.0663, -0.0513, -0.2533]],
 
         [[-0.2413, -0.2596,  0.0677,  ..., -0.3226, -0.2722,  0.0428]],
 
         [[-0.3580, -0.2199,  0.1057,  ..., -0.4245, -0.1274, -0.1684]],
 
         ...,
 
         [[ 0.0548, -0.1895,  0.2044,  ..., -0.1717, -0.0399, -0.4458]],
 
         [[-0.4253, -0.1330,  0.2297,  ..., -0.0894, -0.3153, -0.0024]],
 
         [[ 0.3383, -0.3714,  0.1133,  ..., -0.2130, -0.5707, -0.3244]]],
        grad_fn=<UnsafeViewBackward>),
 tensor([[[-0.2178, -0.7679,  0.3845,  ..., -0.3689, -0.1235, -0.0775]],
 
         [[ 0.0585, -0.3150, -0.0128,  ..., -0.1331, -0.4211,  0.0074]],
 
         [[-0.1434, -0.6870,  0.3764,  ..., -0.3170, -0.5484,  0.1398]],
 
         ...,
 
         [[-0.5725, -0.4409,  0.1626,  ..., -0.2190,  0.0581,  0.1792]],
 
         [[-0.2191, -0.0973,  0.2855,  ...,  0.1174, -0.3680, -0.3544]],
 
         [[-0.1195, -0.1326,  0.0024,  ..., -0.1083, -0.4301, -0.5896]]],
        grad_fn=<UnsafeViewBack

In [6]:
from models.fc_single_model import FC_cat_model

In [11]:
model = FC_cat_model(4096//2, 5, sizes=[1000,100,100,1000,4096//2], bias = False, use_batchnorm= True, dropout= 0.1)

In [12]:
print(model)

FC_cat_model(
  (layers): ModuleList(
    (0): Linear(in_features=4096, out_features=2000, bias=False)
    (1): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=2000, out_features=200, bias=False)
    (5): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.1, inplace=False)
    (8): Linear(in_features=200, out_features=200, bias=False)
    (9): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Dropout(p=0.1, inplace=False)
    (12): Linear(in_features=200, out_features=2000, bias=False)
    (13): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (14): ReLU()
    (15): Dropout(p=0.1, inplace=False)
    (16): Linear(in_features=2000, out_features=4096, bias=False)
  )
)


In [14]:
x = torch.rand((32,1,4096))

In [15]:
model(x)

tensor([[[-0.8631, -0.1278,  0.2622,  ...,  0.1647,  0.1729,  0.1170]],

        [[-0.5459, -0.2896,  0.2046,  ..., -0.2735, -0.0197,  0.4249]],

        [[-0.4549, -0.4921, -0.0825,  ..., -0.3426,  0.2729,  0.5932]],

        ...,

        [[-0.3175, -0.5863,  0.2187,  ..., -0.2515,  0.6263,  0.2897]],

        [[-0.9363, -0.0503,  0.1822,  ..., -0.1445, -0.2353,  0.4471]],

        [[-0.7627, -0.1855,  0.2294,  ...,  0.1208,  0.0626,  0.6577]]],
       grad_fn=<UnsafeViewBackward>)